### Chamar cardapio
GET http://localhost:3000/cardapio/ HTTP/1.1
content-type: application/json

### Chamar promocoes
GET http://localhost:3000/cardapio/promocoes HTTP/1.1
content-type: application/json

### Chamar produto
GET http://localhost:3000/produto/1 HTTP/1.1
content-type: application/json

### Paths
GET http://localhost:3000/paths/ HTTP/1.1
content-type: application/json