### Criar Cliente
POST http://localhost:3000/cliente/ HTTP/1.1
content-type: application/json

{
    "cli_nome": "234"
}

### Logar Cliente
POST http://localhost:3000/cliente/autenticar/ HTTP/1.1
content-type: application/json

{
    "cli_nome": "234",
    "cli_token": "4f5a2dcb-6782-429f-aa20-ad824197befe"
}