### Criar Cliente
POST http://localhost:3000/cliente/ HTTP/1.1
content-type: application/json

{
    "cli_nome": "001a"
}

### Logar Cliente
POST http://localhost:3000/cliente/autenticar/ HTTP/1.1
content-type: application/json

{
    "cli_nome": "234a",
    "cli_token": "0a45ada7-c2f2-452f-9445-7df094b4fdfb"
}
