### Criar Colaborador
POST http://localhost:3000/colaborador/ HTTP/1.1
content-type: application/json

{
    "col_nome": "Teste",
    "fun_id": 1,
    "col_email": "sim@gmail.com",
    "col_senha": "123"
}

### Logar Colaborador
POST http://localhost:3000/colaborador/autenticar/ HTTP/1.1
content-type: application/json

{
    "col_email": "Josimar@gmail.com",
    "col_senha": "123"
}